// ICD Code Dictionary — curated for clinical trial use
// Format: { code, description }

export const ICD10 = [
    // ── Infectious & Parasitic (A00–B99) ─────────────────────
    { code:'A00',  description:'Cholera' },
    { code:'A01',  description:'Typhoid and paratyphoid fevers' },
    { code:'A02',  description:'Other Salmonella infections' },
    { code:'A04',  description:'Other bacterial intestinal infections' },
    { code:'A09',  description:'Infectious gastroenteritis and colitis' },
    { code:'A15',  description:'Respiratory tuberculosis' },
    { code:'A16',  description:'Tuberculosis of respiratory system, unconfirmed' },
    { code:'A41',  description:'Sepsis' },
    { code:'A49',  description:'Bacterial infection, unspecified' },
    { code:'B00',  description:'Herpesviral infections' },
    { code:'B02',  description:'Zoster (herpes zoster)' },
    { code:'B18',  description:'Chronic viral hepatitis' },
    { code:'B18.1',description:'Chronic viral hepatitis B without delta-agent' },
    { code:'B18.2',description:'Chronic viral hepatitis C' },
    { code:'B20',  description:'HIV disease resulting in infectious diseases' },
    { code:'B34',  description:'Viral infection, unspecified site' },

    // ── Neoplasms (C00–D49) ───────────────────────────────────
    { code:'C18',  description:'Malignant neoplasm of colon' },
    { code:'C20',  description:'Malignant neoplasm of rectum' },
    { code:'C22',  description:'Malignant neoplasm of liver' },
    { code:'C25',  description:'Malignant neoplasm of pancreas' },
    { code:'C34',  description:'Malignant neoplasm of bronchus and lung' },
    { code:'C43',  description:'Malignant melanoma of skin' },
    { code:'C50',  description:'Malignant neoplasm of breast' },
    { code:'C53',  description:'Malignant neoplasm of cervix uteri' },
    { code:'C54',  description:'Malignant neoplasm of corpus uteri' },
    { code:'C56',  description:'Malignant neoplasm of ovary' },
    { code:'C61',  description:'Malignant neoplasm of prostate' },
    { code:'C67',  description:'Malignant neoplasm of bladder' },
    { code:'C71',  description:'Malignant neoplasm of brain' },
    { code:'C73',  description:'Malignant neoplasm of thyroid gland' },
    { code:'C80',  description:'Malignant neoplasm, primary site unknown' },
    { code:'C90',  description:'Multiple myeloma' },
    { code:'C91',  description:'Lymphoid leukaemia' },
    { code:'C92',  description:'Myeloid leukaemia' },
    { code:'D12',  description:'Benign neoplasm of colon, rectum, anus and anal canal' },
    { code:'D25',  description:'Leiomyoma of uterus' },
    { code:'D48',  description:'Neoplasm of uncertain behaviour of other and unspecified sites' },

    // ── Blood & Immune (D50–D89) ──────────────────────────────
    { code:'D50',  description:'Iron deficiency anaemia' },
    { code:'D51',  description:'Vitamin B12 deficiency anaemia' },
    { code:'D55',  description:'Anaemia due to enzyme disorders' },
    { code:'D57',  description:'Sickle-cell disorders' },
    { code:'D64',  description:'Other anaemias' },
    { code:'D68',  description:'Other coagulation defects' },
    { code:'D69',  description:'Purpura and other haemorrhagic conditions' },
    { code:'D70',  description:'Neutropenia' },
    { code:'D80',  description:'Immunodeficiency with predominantly antibody defects' },

    // ── Endocrine / Metabolic (E00–E89) ──────────────────────
    { code:'E00',  description:'Congenital iodine-deficiency syndrome' },
    { code:'E01',  description:'Iodine-deficiency-related thyroid disorders' },
    { code:'E03',  description:'Other hypothyroidism' },
    { code:'E04',  description:'Other non-toxic goitre' },
    { code:'E05',  description:'Thyrotoxicosis (hyperthyroidism)' },
    { code:'E06',  description:'Thyroiditis' },
    { code:'E08',  description:'Diabetes mellitus due to underlying condition' },
    { code:'E09',  description:'Drug or chemical induced diabetes mellitus' },
    { code:'E10',  description:'Type 1 diabetes mellitus' },
    { code:'E11',  description:'Type 2 diabetes mellitus' },
    { code:'E11.0',description:'Type 2 diabetes mellitus with hyperosmolarity' },
    { code:'E11.1',description:'Type 2 diabetes mellitus with ketoacidosis' },
    { code:'E11.2',description:'Type 2 diabetes mellitus with kidney complications' },
    { code:'E11.3',description:'Type 2 diabetes mellitus with ophthalmic complications' },
    { code:'E11.4',description:'Type 2 diabetes mellitus with neurological complications' },
    { code:'E11.5',description:'Type 2 diabetes mellitus with circulatory complications' },
    { code:'E11.6',description:'Type 2 diabetes mellitus with other specified complications' },
    { code:'E11.7',description:'Type 2 diabetes mellitus with multiple complications' },
    { code:'E11.9',description:'Type 2 diabetes mellitus without complications' },
    { code:'E12',  description:'Malnutrition-related diabetes mellitus' },
    { code:'E13',  description:'Other specified diabetes mellitus' },
    { code:'E14',  description:'Unspecified diabetes mellitus' },
    { code:'E16',  description:'Other disorders of pancreatic internal secretion' },
    { code:'E20',  description:'Hypoparathyroidism' },
    { code:'E21',  description:'Hyperparathyroidism' },
    { code:'E22',  description:'Hyperfunction of pituitary gland' },
    { code:'E23',  description:'Hypofunction and other disorders of the pituitary gland' },
    { code:'E24',  description:"Cushing's syndrome" },
    { code:'E25',  description:'Adrenogenital disorders' },
    { code:'E26',  description:'Hyperaldosteronism' },
    { code:'E27',  description:'Other disorders of adrenal gland' },
    { code:'E28',  description:'Ovarian dysfunction' },
    { code:'E29',  description:'Testicular dysfunction' },
    { code:'E34',  description:'Other endocrine disorders' },
    { code:'E40',  description:'Kwashiorkor' },
    { code:'E41',  description:'Nutritional marasmus' },
    { code:'E44',  description:'Protein-energy malnutrition of moderate and mild degree' },
    { code:'E46',  description:'Unspecified protein-energy malnutrition' },
    { code:'E50',  description:'Vitamin A deficiency' },
    { code:'E55',  description:'Vitamin D deficiency' },
    { code:'E58',  description:'Dietary calcium deficiency' },
    { code:'E61',  description:'Deficiency of other nutrient elements' },
    { code:'E63',  description:'Other nutritional deficiencies' },
    { code:'E66',  description:'Obesity' },
    { code:'E66.0',description:'Obesity due to excess calories' },
    { code:'E66.1',description:'Drug-induced obesity' },
    { code:'E66.9',description:'Obesity, unspecified' },
    { code:'E70',  description:'Disorders of aromatic amino-acid metabolism' },
    { code:'E72',  description:'Other disorders of amino-acid metabolism' },
    { code:'E73',  description:'Lactose intolerance' },
    { code:'E74',  description:'Other disorders of carbohydrate metabolism' },
    { code:'E75',  description:'Disorders of sphingolipid metabolism' },
    { code:'E76',  description:'Disorders of glycosaminoglycan metabolism' },
    { code:'E78',  description:'Disorders of lipoprotein metabolism and other lipaemias' },
    { code:'E78.0',description:'Pure hypercholesterolaemia' },
    { code:'E78.1',description:'Pure hyperglyceridaemia' },
    { code:'E78.2',description:'Mixed hyperlipidaemia' },
    { code:'E78.3',description:'Hyperchylomicronaemia' },
    { code:'E78.4',description:'Other hyperlipidaemia' },
    { code:'E78.5',description:'Hyperlipidaemia, unspecified' },
    { code:'E79',  description:'Disorders of purine and pyrimidine metabolism' },
    { code:'E80',  description:'Disorders of porphyrin and bilirubin metabolism' },
    { code:'E83',  description:'Disorders of mineral metabolism' },
    { code:'E84',  description:'Cystic fibrosis' },
    { code:'E85',  description:'Amyloidosis' },
    { code:'E86',  description:'Volume depletion / dehydration' },
    { code:'E87',  description:'Other disorders of fluid, electrolyte and acid-base balance' },
    { code:'E88',  description:'Other metabolic disorders' },

    // ── Mental & Behavioural (F01–F99) ───────────────────────
    { code:'F01',  description:'Vascular dementia' },
    { code:'F03',  description:'Unspecified dementia' },
    { code:'F05',  description:'Delirium, not induced by alcohol and other psychoactive substances' },
    { code:'F06',  description:'Other mental disorders due to brain damage and dysfunction' },
    { code:'F10',  description:'Mental and behavioural disorders due to use of alcohol' },
    { code:'F17',  description:'Mental and behavioural disorders due to use of tobacco' },
    { code:'F20',  description:'Schizophrenia' },
    { code:'F25',  description:'Schizoaffective disorders' },
    { code:'F31',  description:'Bipolar affective disorder' },
    { code:'F32',  description:'Depressive episode' },
    { code:'F33',  description:'Recurrent depressive disorder' },
    { code:'F40',  description:'Phobic anxiety disorders' },
    { code:'F41',  description:'Other anxiety disorders' },
    { code:'F41.1',description:'Generalized anxiety disorder' },
    { code:'F43',  description:'Reaction to severe stress, and adjustment disorders' },
    { code:'F45',  description:'Somatoform disorders' },
    { code:'F50',  description:'Eating disorders' },
    { code:'F60',  description:'Specific personality disorders' },
    { code:'F70',  description:'Mild intellectual disability' },
    { code:'F90',  description:'Hyperkinetic disorders (ADHD)' },

    // ── Nervous System (G00–G99) ──────────────────────────────
    { code:'G00',  description:'Bacterial meningitis' },
    { code:'G10',  description:"Huntington's disease" },
    { code:'G20',  description:"Parkinson's disease" },
    { code:'G25',  description:'Other extrapyramidal and movement disorders' },
    { code:'G30',  description:"Alzheimer's disease" },
    { code:'G35',  description:'Multiple sclerosis' },
    { code:'G40',  description:'Epilepsy' },
    { code:'G43',  description:'Migraine' },
    { code:'G45',  description:'Transient cerebral ischaemic attacks and related syndromes' },
    { code:'G47',  description:'Sleep disorders' },
    { code:'G51',  description:"Bell's palsy / facial nerve disorders" },
    { code:'G54',  description:'Nerve root and plexus disorders' },
    { code:'G56',  description:'Mononeuropathies of upper limb' },
    { code:'G57',  description:'Mononeuropathies of lower limb' },
    { code:'G60',  description:'Hereditary and idiopathic neuropathy' },
    { code:'G61',  description:'Inflammatory polyneuropathy (Guillain-Barré)' },
    { code:'G62',  description:'Other polyneuropathies' },
    { code:'G63',  description:'Polyneuropathy in diseases classified elsewhere' },
    { code:'G70',  description:'Myasthenia gravis and other myoneural disorders' },
    { code:'G80',  description:'Cerebral palsy' },
    { code:'G89',  description:'Pain, not elsewhere classified' },
    { code:'G93',  description:'Other disorders of brain' },

    // ── Eye (H00–H59) ─────────────────────────────────────────
    { code:'H25',  description:'Age-related cataract' },
    { code:'H26',  description:'Other cataract' },
    { code:'H33',  description:'Retinal detachments and breaks' },
    { code:'H35',  description:'Other retinal disorders' },
    { code:'H36',  description:'Retinal disorders in diseases classified elsewhere (diabetic retinopathy)' },
    { code:'H40',  description:'Glaucoma' },
    { code:'H52',  description:'Disorders of refraction and accommodation' },

    // ── Circulatory System (I00–I99) ──────────────────────────
    { code:'I05',  description:'Rheumatic mitral valve diseases' },
    { code:'I06',  description:'Rheumatic aortic valve diseases' },
    { code:'I10',  description:'Essential (primary) hypertension' },
    { code:'I11',  description:'Hypertensive heart disease' },
    { code:'I12',  description:'Hypertensive renal disease' },
    { code:'I13',  description:'Hypertensive heart and renal disease' },
    { code:'I15',  description:'Secondary hypertension' },
    { code:'I20',  description:'Angina pectoris' },
    { code:'I20.0',description:'Unstable angina' },
    { code:'I20.1',description:'Angina pectoris with documented spasm' },
    { code:'I20.9',description:'Angina pectoris, unspecified' },
    { code:'I21',  description:'Acute myocardial infarction (STEMI/NSTEMI)' },
    { code:'I21.0',description:'Acute transmural MI of anterior wall (STEMI)' },
    { code:'I21.1',description:'Acute transmural MI of inferior wall (STEMI)' },
    { code:'I21.4',description:'Acute subendocardial MI (NSTEMI)' },
    { code:'I21.9',description:'Acute myocardial infarction, unspecified' },
    { code:'I22',  description:'Subsequent myocardial infarction' },
    { code:'I25',  description:'Chronic ischaemic heart disease' },
    { code:'I25.1',description:'Atherosclerotic heart disease' },
    { code:'I25.2',description:'Old myocardial infarction' },
    { code:'I25.5',description:'Ischaemic cardiomyopathy' },
    { code:'I26',  description:'Pulmonary embolism' },
    { code:'I27',  description:'Other pulmonary heart diseases' },
    { code:'I30',  description:'Acute pericarditis' },
    { code:'I34',  description:'Non-rheumatic mitral valve disorders' },
    { code:'I35',  description:'Non-rheumatic aortic valve disorders' },
    { code:'I38',  description:'Endocarditis, valve unspecified' },
    { code:'I42',  description:'Cardiomyopathy' },
    { code:'I44',  description:'Atrioventricular and left bundle-branch block' },
    { code:'I45',  description:'Other conduction disorders' },
    { code:'I46',  description:'Cardiac arrest' },
    { code:'I47',  description:'Paroxysmal tachycardia' },
    { code:'I48',  description:'Atrial fibrillation and flutter' },
    { code:'I49',  description:'Other cardiac arrhythmias' },
    { code:'I50',  description:'Heart failure' },
    { code:'I50.0',description:'Congestive heart failure' },
    { code:'I50.1',description:'Left ventricular failure' },
    { code:'I50.9',description:'Heart failure, unspecified' },
    { code:'I51',  description:'Complications and ill-defined descriptions of heart disease' },
    { code:'I60',  description:'Subarachnoid haemorrhage' },
    { code:'I61',  description:'Intracerebral haemorrhage' },
    { code:'I63',  description:'Cerebral infarction (ischaemic stroke)' },
    { code:'I64',  description:'Stroke, not specified as haemorrhage or infarction' },
    { code:'I65',  description:'Occlusion and stenosis of precerebral arteries' },
    { code:'I66',  description:'Occlusion and stenosis of cerebral arteries' },
    { code:'I67',  description:'Other cerebrovascular diseases' },
    { code:'I69',  description:'Sequelae of cerebrovascular disease' },
    { code:'I70',  description:'Atherosclerosis' },
    { code:'I70.0',description:'Atherosclerosis of aorta' },
    { code:'I70.1',description:'Atherosclerosis of renal artery' },
    { code:'I70.2',description:'Atherosclerosis of arteries of the extremities' },
    { code:'I71',  description:'Aortic aneurysm and dissection' },
    { code:'I72',  description:'Other aneurysm' },
    { code:'I73',  description:'Other peripheral vascular diseases' },
    { code:'I74',  description:'Arterial embolism and thrombosis' },
    { code:'I77',  description:'Other disorders of arteries and arterioles' },
    { code:'I80',  description:'Phlebitis and thrombophlebitis (DVT)' },
    { code:'I82',  description:'Other venous embolism and thrombosis' },
    { code:'I83',  description:'Varicose veins of lower extremities' },
    { code:'I87',  description:'Other disorders of veins' },
    { code:'I89',  description:'Other non-infective disorders of lymphatic vessels' },
    { code:'I95',  description:'Hypotension' },
    { code:'I97',  description:'Postprocedural disorders of circulatory system' },

    // ── Respiratory (J00–J99) ─────────────────────────────────
    { code:'J00',  description:'Acute nasopharyngitis (common cold)' },
    { code:'J02',  description:'Acute pharyngitis' },
    { code:'J03',  description:'Acute tonsillitis' },
    { code:'J04',  description:'Acute laryngitis and tracheitis' },
    { code:'J06',  description:'Acute upper respiratory infections, multiple sites' },
    { code:'J10',  description:'Influenza due to identified seasonal influenza virus' },
    { code:'J11',  description:'Influenza, virus not identified' },
    { code:'J12',  description:'Viral pneumonia' },
    { code:'J13',  description:'Pneumonia due to Streptococcus pneumoniae' },
    { code:'J18',  description:'Pneumonia, organism unspecified' },
    { code:'J20',  description:'Acute bronchitis' },
    { code:'J22',  description:'Unspecified acute lower respiratory infection' },
    { code:'J30',  description:'Vasomotor and allergic rhinitis' },
    { code:'J32',  description:'Chronic sinusitis' },
    { code:'J35',  description:'Chronic diseases of tonsils and adenoids' },
    { code:'J40',  description:'Bronchitis, not specified as acute or chronic' },
    { code:'J41',  description:'Simple and mucopurulent chronic bronchitis' },
    { code:'J42',  description:'Unspecified chronic bronchitis' },
    { code:'J43',  description:'Emphysema' },
    { code:'J44',  description:'Chronic obstructive pulmonary disease (COPD)' },
    { code:'J45',  description:'Asthma' },
    { code:'J45.0',description:'Predominantly allergic asthma' },
    { code:'J45.1',description:'Nonallergic asthma' },
    { code:'J45.9',description:'Asthma, unspecified' },
    { code:'J46',  description:'Status asthmaticus' },
    { code:'J47',  description:'Bronchiectasis' },
    { code:'J60',  description:'Coalworker pneumoconiosis' },
    { code:'J68',  description:'Respiratory conditions due to inhalation of chemicals' },
    { code:'J70',  description:'Respiratory conditions due to other external agents' },
    { code:'J80',  description:'Acute respiratory distress syndrome (ARDS)' },
    { code:'J84',  description:'Other interstitial pulmonary diseases' },
    { code:'J90',  description:'Pleural effusion' },
    { code:'J91',  description:'Pleural effusion in conditions classified elsewhere' },
    { code:'J93',  description:'Pneumothorax' },
    { code:'J96',  description:'Respiratory failure' },

    // ── Digestive (K00–K93) ───────────────────────────────────
    { code:'K00',  description:'Disorders of tooth development and eruption' },
    { code:'K05',  description:'Gingivitis and periodontal diseases' },
    { code:'K21',  description:'Gastro-oesophageal reflux disease (GERD)' },
    { code:'K25',  description:'Gastric ulcer' },
    { code:'K26',  description:'Duodenal ulcer' },
    { code:'K27',  description:'Peptic ulcer' },
    { code:'K29',  description:'Gastritis and duodenitis' },
    { code:'K30',  description:'Functional dyspepsia' },
    { code:'K35',  description:'Acute appendicitis' },
    { code:'K40',  description:'Inguinal hernia' },
    { code:'K41',  description:'Femoral hernia' },
    { code:'K42',  description:'Umbilical hernia' },
    { code:'K43',  description:'Ventral hernia' },
    { code:'K44',  description:'Diaphragmatic hernia' },
    { code:'K46',  description:'Unspecified abdominal hernia' },
    { code:'K50',  description:"Crohn's disease" },
    { code:'K51',  description:'Ulcerative colitis' },
    { code:'K57',  description:'Diverticular disease of intestine' },
    { code:'K59',  description:'Other functional intestinal disorders' },
    { code:'K70',  description:'Alcoholic liver disease' },
    { code:'K71',  description:'Toxic liver disease' },
    { code:'K72',  description:'Hepatic failure' },
    { code:'K73',  description:'Chronic hepatitis' },
    { code:'K74',  description:'Fibrosis and cirrhosis of liver' },
    { code:'K75',  description:'Other inflammatory liver diseases' },
    { code:'K76',  description:'Other diseases of liver (NAFLD/NASH)' },
    { code:'K80',  description:'Cholelithiasis (gallstones)' },
    { code:'K81',  description:'Cholecystitis' },
    { code:'K85',  description:'Acute pancreatitis' },
    { code:'K86',  description:'Other diseases of pancreas (chronic pancreatitis)' },
    { code:'K90',  description:'Intestinal malabsorption' },
    { code:'K92',  description:'Other diseases of digestive system (GI bleeding)' },

    // ── Musculoskeletal (M00–M99) ─────────────────────────────
    { code:'M00',  description:'Pyogenic arthritis' },
    { code:'M05',  description:'Seropositive rheumatoid arthritis' },
    { code:'M06',  description:'Other rheumatoid arthritis' },
    { code:'M08',  description:'Juvenile arthritis' },
    { code:'M10',  description:'Gout' },
    { code:'M10.0',description:'Idiopathic gout' },
    { code:'M10.1',description:'Lead-induced gout' },
    { code:'M10.3',description:'Gout due to renal impairment' },
    { code:'M11',  description:'Other crystal arthropathies' },
    { code:'M15',  description:'Polyarthrosis (multiple joint osteoarthritis)' },
    { code:'M16',  description:'Osteoarthrosis of hip' },
    { code:'M17',  description:'Osteoarthrosis of knee' },
    { code:'M19',  description:'Other arthrosis' },
    { code:'M25',  description:'Other joint disorders' },
    { code:'M32',  description:'Systemic lupus erythematosus (SLE)' },
    { code:'M33',  description:'Dermatopolymyositis' },
    { code:'M34',  description:'Systemic sclerosis (scleroderma)' },
    { code:'M35',  description:"Sjögren's syndrome and other systemic disorders" },
    { code:'M40',  description:'Kyphosis and lordosis' },
    { code:'M41',  description:'Scoliosis' },
    { code:'M47',  description:'Spondylosis' },
    { code:'M48',  description:'Other spondylopathies' },
    { code:'M50',  description:'Cervical disc disorders' },
    { code:'M51',  description:'Other intervertebral disc disorders (lumbar)' },
    { code:'M54',  description:'Dorsalgia (back pain)' },
    { code:'M54.5',description:'Low back pain' },
    { code:'M60',  description:'Myositis (including statin-induced)' },
    { code:'M62',  description:'Other disorders of muscle' },
    { code:'M65',  description:'Synovitis and tenosynovitis' },
    { code:'M70',  description:'Soft tissue disorders related to use, overuse and pressure' },
    { code:'M75',  description:'Shoulder lesions (rotator cuff)' },
    { code:'M79',  description:'Other soft tissue disorders (fibromyalgia)' },
    { code:'M80',  description:'Osteoporosis with current pathological fracture' },
    { code:'M81',  description:'Osteoporosis without current pathological fracture' },
    { code:'M85',  description:'Other disorders of bone density and structure' },

    // ── Genitourinary (N00–N99) ───────────────────────────────
    { code:'N00',  description:'Acute nephritic syndrome' },
    { code:'N03',  description:'Chronic nephritic syndrome' },
    { code:'N04',  description:'Nephrotic syndrome' },
    { code:'N05',  description:'Unspecified nephritic syndrome' },
    { code:'N08',  description:'Glomerular disorders in diseases classified elsewhere (diabetic nephropathy)' },
    { code:'N10',  description:'Acute tubulo-interstitial nephritis' },
    { code:'N11',  description:'Chronic tubulo-interstitial nephritis' },
    { code:'N17',  description:'Acute kidney failure' },
    { code:'N18',  description:'Chronic kidney disease (CKD)' },
    { code:'N18.1',description:'Chronic kidney disease, stage 1' },
    { code:'N18.2',description:'Chronic kidney disease, stage 2' },
    { code:'N18.3',description:'Chronic kidney disease, stage 3' },
    { code:'N18.4',description:'Chronic kidney disease, stage 4' },
    { code:'N18.5',description:'Chronic kidney disease, stage 5 (pre-dialysis)' },
    { code:'N18.6',description:'End-stage renal disease (dialysis)' },
    { code:'N19',  description:'Unspecified kidney failure' },
    { code:'N20',  description:'Calculus of kidney and ureter (nephrolithiasis)' },
    { code:'N28',  description:'Other disorders of kidney and ureter' },
    { code:'N30',  description:'Cystitis' },
    { code:'N35',  description:'Urethral stricture' },
    { code:'N39',  description:'Other disorders of urinary system (UTI)' },
    { code:'N40',  description:'Benign prostatic hyperplasia (BPH)' },
    { code:'N46',  description:'Male infertility' },
    { code:'N52',  description:'Male erectile dysfunction' },
    { code:'N73',  description:'Other female pelvic inflammatory diseases' },
    { code:'N80',  description:'Endometriosis' },
    { code:'N83',  description:'Non-inflammatory disorders of ovary, fallopian tube' },
    { code:'N95',  description:'Menopausal and other perimenopausal disorders' },

    // ── Symptoms / Signs (R00–R99) ────────────────────────────
    { code:'R00',  description:'Abnormalities of heart beat' },
    { code:'R03',  description:'Abnormal blood-pressure reading' },
    { code:'R05',  description:'Cough' },
    { code:'R06',  description:'Abnormalities of breathing (dyspnoea)' },
    { code:'R07',  description:'Pain in throat and chest' },
    { code:'R10',  description:'Abdominal and pelvic pain' },
    { code:'R11',  description:'Nausea and vomiting' },
    { code:'R12',  description:'Heartburn' },
    { code:'R13',  description:'Dysphagia' },
    { code:'R14',  description:'Flatulence and related conditions' },
    { code:'R25',  description:'Abnormal involuntary movements' },
    { code:'R41',  description:'Other symptoms involving cognitive functions (memory loss)' },
    { code:'R50',  description:'Fever of other and unknown origin' },
    { code:'R51',  description:'Headache' },
    { code:'R53',  description:'Malaise and fatigue' },
    { code:'R55',  description:'Syncope and collapse' },
    { code:'R58',  description:'Haemorrhage, not elsewhere classified' },
    { code:'R60',  description:'Oedema, not elsewhere classified' },
    { code:'R63',  description:'Symptoms concerning food and fluid intake (anorexia, polydipsia)' },
    { code:'R68',  description:'Other general symptoms and signs' },
    { code:'R73',  description:'Elevated blood glucose level (pre-diabetes / impaired glucose)' },
    { code:'R74',  description:'Abnormal serum enzyme levels (elevated creatinine kinase)' },
    { code:'R79',  description:'Other abnormal findings of blood chemistry' },

    // ── Z Codes (Factors influencing health) ─────────────────
    { code:'Z82.3',description:'Family history of stroke' },
    { code:'Z82.4',description:'Family history of ischaemic heart disease' },
    { code:'Z82.49',description:'Family history of other cardiovascular disease' },
    { code:'Z83.3',description:'Family history of diabetes mellitus' },
    { code:'Z87.39',description:'Personal history of other endocrine, nutritional and metabolic diseases' },
    { code:'Z95.0',description:'Presence of cardiac pacemaker' },
    { code:'Z95.1',description:'Presence of aortocoronary bypass graft' },
    { code:'Z95.5',description:'Presence of coronary angioplasty implant and graft' },
    { code:'Z96.64',description:'Presence of artificial hip joint' },
    { code:'Z96.65',description:'Presence of artificial knee joint' },
];

export const ICD11 = [
    { code:'1A00',  description:'Cholera' },
    { code:'1C80',  description:'Sepsis' },
    { code:'2C00',  description:'Neoplasm of colon' },
    { code:'2C60',  description:'Lung neoplasm' },
    { code:'2C71',  description:'Neoplasm of breast' },
    { code:'3A00',  description:'Iron deficiency anaemia' },
    { code:'5A00',  description:'Type 1 diabetes mellitus' },
    { code:'5A10',  description:'Type 2 diabetes mellitus' },
    { code:'5A10.0',description:'Type 2 DM without complications' },
    { code:'5A10.1',description:'Type 2 DM with diabetic ketoacidosis' },
    { code:'5A10.2',description:'Type 2 DM with hyperosmolarity' },
    { code:'5A10.3',description:'Type 2 DM with diabetic nephropathy' },
    { code:'5A10.4',description:'Type 2 DM with diabetic neuropathy' },
    { code:'5A10.5',description:'Type 2 DM with diabetic retinopathy' },
    { code:'5A10.6',description:'Type 2 DM with other complications' },
    { code:'5A11',  description:'Type 2 diabetes mellitus, unspecified' },
    { code:'5B80',  description:'Obesity' },
    { code:'5B81',  description:'Overweight' },
    { code:'6A00',  description:'Single episode depressive disorder' },
    { code:'6A20',  description:'Bipolar type I disorder' },
    { code:'6A40',  description:'Generalised anxiety disorder' },
    { code:'6D80',  description:"Alzheimer's disease dementia" },
    { code:'8A00',  description:'Epilepsy or seizures' },
    { code:'8B00',  description:'Stroke — ischaemic' },
    { code:'8B01',  description:'Stroke — haemorrhagic' },
    { code:'BA00',  description:'Essential hypertension' },
    { code:'BA80',  description:'Acute myocardial infarction' },
    { code:'BA81',  description:'Coronary artery disease' },
    { code:'BA82',  description:'Unstable angina' },
    { code:'BB00',  description:'Heart failure' },
    { code:'BB40',  description:'Atrial fibrillation' },
    { code:'BB41',  description:'Atrial flutter' },
    { code:'BC50',  description:'Peripheral artery disease' },
    { code:'BC51',  description:'Deep vein thrombosis (DVT)' },
    { code:'BC52',  description:'Pulmonary embolism' },
    { code:'CA22',  description:'Asthma' },
    { code:'CA23',  description:'Chronic obstructive pulmonary disease (COPD)' },
    { code:'CA25',  description:'Bronchiectasis' },
    { code:'DA90',  description:'Gastroesophageal reflux disease (GERD)' },
    { code:'DA91',  description:'Gastric ulcer' },
    { code:'DA92',  description:'Duodenal ulcer' },
    { code:'DC30',  description:"Crohn's disease" },
    { code:'DC31',  description:'Ulcerative colitis' },
    { code:'DB92',  description:'Non-alcoholic fatty liver disease (NAFLD)' },
    { code:'DB95',  description:'Cirrhosis of liver' },
    { code:'FA20',  description:'Rheumatoid arthritis' },
    { code:'FA30',  description:'Gout' },
    { code:'FA80',  description:'Osteoarthritis' },
    { code:'FB83',  description:'Osteoporosis' },
    { code:'GB60',  description:'Chronic kidney disease (CKD)' },
    { code:'GB60.0',description:'CKD stage 1' },
    { code:'GB60.1',description:'CKD stage 2' },
    { code:'GB60.2',description:'CKD stage 3' },
    { code:'GB60.3',description:'CKD stage 4' },
    { code:'GB60.4',description:'CKD stage 5' },
    { code:'5C80',  description:'Dyslipidaemia (hypercholesterolaemia)' },
    { code:'5C81',  description:'Mixed dyslipidaemia' },
];

export const ICD9 = [
    { code:'001',   description:'Cholera' },
    { code:'038',   description:'Septicaemia' },
    { code:'140-239',description:'Neoplasms' },
    { code:'250',   description:'Diabetes mellitus' },
    { code:'250.0', description:'Diabetes mellitus, type 2, without complications' },
    { code:'250.1', description:'Diabetes with ketoacidosis' },
    { code:'250.4', description:'Diabetes with renal manifestations (diabetic nephropathy)' },
    { code:'272',   description:'Disorders of lipoid metabolism (hyperlipidaemia)' },
    { code:'272.0', description:'Pure hypercholesterolaemia' },
    { code:'272.2', description:'Mixed hyperlipidaemia' },
    { code:'278',   description:'Obesity and other hyperalimentation' },
    { code:'293',   description:'Transient mental disorders due to conditions elsewhere' },
    { code:'311',   description:'Depressive disorder' },
    { code:'331',   description:'Other cerebral degenerations (Alzheimer)' },
    { code:'332',   description:"Parkinson's disease" },
    { code:'345',   description:'Epilepsy and recurrent seizures' },
    { code:'362.0', description:'Diabetic retinopathy' },
    { code:'401',   description:'Essential hypertension' },
    { code:'410',   description:'Acute myocardial infarction' },
    { code:'411',   description:'Other acute and subacute forms of ischaemic heart disease' },
    { code:'412',   description:'Old myocardial infarction' },
    { code:'413',   description:'Angina pectoris' },
    { code:'414',   description:'Other forms of chronic ischaemic heart disease' },
    { code:'427',   description:'Cardiac dysrhythmias (atrial fibrillation)' },
    { code:'428',   description:'Heart failure' },
    { code:'430',   description:'Subarachnoid haemorrhage' },
    { code:'433',   description:'Occlusion and stenosis of precerebral arteries' },
    { code:'434',   description:'Occlusion of cerebral arteries (ischaemic stroke)' },
    { code:'440',   description:'Atherosclerosis' },
    { code:'491',   description:'Chronic bronchitis' },
    { code:'492',   description:'Emphysema' },
    { code:'493',   description:'Asthma' },
    { code:'496',   description:'COPD' },
    { code:'530.11',description:'Gastroesophageal reflux with oesophagitis (GERD)' },
    { code:'531',   description:'Gastric ulcer' },
    { code:'532',   description:'Duodenal ulcer' },
    { code:'555',   description:"Crohn's disease" },
    { code:'556',   description:'Ulcerative colitis' },
    { code:'571',   description:'Liver disease (alcoholic / cirrhosis)' },
    { code:'584',   description:'Acute kidney failure' },
    { code:'585',   description:'Chronic kidney disease (CKD)' },
    { code:'590',   description:'Infections of kidney (pyelonephritis)' },
    { code:'600',   description:'Hyperplasia of prostate (BPH)' },
    { code:'710.0', description:'Systemic lupus erythematosus (SLE)' },
    { code:'715',   description:'Osteoarthrosis (osteoarthritis)' },
    { code:'716',   description:'Other and unspecified arthropathies' },
    { code:'720',   description:'Ankylosing spondylitis and other inflammatory spondylopathies' },
    { code:'724',   description:'Other and unspecified disorders of back (low back pain)' },
    { code:'733',   description:'Other disorders of bone and cartilage (osteoporosis)' },
    { code:'401',   description:'Essential hypertension' },
];

export const ICD_VERSIONS = { 'ICD-10': ICD10, 'ICD-11': ICD11, 'ICD-9': ICD9 };
