// ============================================================
// Informed consent controls — ICH GCP E6(R3) §4.1.5 / §4.8.8
//
// Two checks that a well-built EDC enforces at entry time rather than leaving
// to the monitor:
//   1. only a delegated person may take consent
//   2. consent must precede the first study procedure
// ============================================================

import { eq, and } from 'drizzle-orm';
import { db } from '../db/connection.js';
import { delegationLog, protocolDeviations, visits, screeningLog, informedConsents } from '../db/schemas/schema.js';
import { writeAudit } from './audit.js';
import {
    CONSENT_TASK, isDelegatedForConsent, earliestProcedure, isConsentLate,
} from './consentrules.js';

export { CONSENT_TASK, eligibleConsentTakers } from './consentrules.js';

// Verify the person who conducted the consent discussion is delegated for it on
// the consent date. A study that has not built its delegation log yet gets a
// warning rather than a hard block — otherwise nobody could enter the first
// consent before the log exists.
export async function checkConsentDelegation(studyId, obtainedBy, consentDate) {
    if (!obtainedBy) return { ok: true };

    const rows = await db.select({
        userId: delegationLog.userId,
        tasks:  delegationLog.delegatedTasks,
        status: delegationLog.status,
        start:  delegationLog.delegationStart,
        end:    delegationLog.delegationEnd,
    }).from(delegationLog).where(eq(delegationLog.studyId, studyId));

    if (rows.length === 0) {
        return {
            ok: true,
            warning: `Delegation Log is empty — the consent taker could not be verified against it (ICH GCP E6(R3) §4.1.5).`,
        };
    }

    if (isDelegatedForConsent(rows, obtainedBy, consentDate)) return { ok: true };

    return {
        ok: false,
        error: `The selected person has no active Delegation Log entry for "${CONSENT_TASK}" covering ${String(consentDate).slice(0, 10)}. Update the Delegation Log first (ICH GCP E6(R3) §4.1.5).`,
    };
}

// Earliest documented study procedure for a subject: the screening visit or any
// visit with a recorded date.
export async function firstProcedureDate(studyId, subjectId) {
    const [visitRows, screenRows] = await Promise.all([
        db.select({
            actualDate: visits.actualDate,
            visitDate:  visits.visitDate,
            visitName:  visits.visitName,
        }).from(visits).where(eq(visits.subjectId, subjectId)),
        db.select({ screeningDate: screeningLog.screeningDate })
            .from(screeningLog)
            .where(and(
                eq(screeningLog.studyId, studyId),
                eq(screeningLog.enrolledSubjectId, subjectId),
            )),
    ]);

    return earliestProcedure(visitRows, screenRows);
}

// Raise a protocol deviation when consent is dated after the first study
// procedure. Idempotent per subject: one auto-generated consent deviation only.
export async function autoCreateLateConsentDeviation(studyId, subjectId, consentDate, user) {
    if (!consentDate) return null;

    const first = await firstProcedureDate(studyId, subjectId);
    if (!first) return null;
    if (!isConsentLate(consentDate, first.date)) return null;

    const signed = String(consentDate).slice(0, 10);

    const existing = await db.select({ id: protocolDeviations.id })
        .from(protocolDeviations)
        .where(and(
            eq(protocolDeviations.subjectId, subjectId),
            eq(protocolDeviations.autoGenerated, true),
            eq(protocolDeviations.category, 'Informed Consent'),
        ))
        .limit(1);
    if (existing.length > 0) return null;

    const today = new Date().toISOString().split('T')[0];
    const description = `Informed consent dated ${signed} was obtained AFTER the first documented study procedure (${first.label}, ${first.date}). Auto-detected per ICH GCP E6(R3) §4.8.8.`;

    const [dev] = await db.insert(protocolDeviations).values({
        studyId,
        subjectId,
        autoGenerated:   true,
        deviationType:   'Consent Deviation',
        category:        'Informed Consent',
        description,
        deviationDate:   first.date,
        discoveryDate:   today,
        rootCause:       'Consent date recorded later than the first documented study procedure.',
        impactOnSubject: 'Under review — investigator to assess; consent deviations are normally reportable to the IRB/EC.',
        status:          'Open',
        createdBy:       user?.id   ?? null,
        createdByName:   user?.name ?? 'System',
    }).returning();

    await writeAudit(db, {
        tableName: 'protocol_deviations', recordId: dev.id, action: 'INSERT',
        newValue: description.substring(0, 100),
        reason: 'Auto-generated: consent obtained after first study procedure',
        user, ipAddress: null,
    });
    return dev;
}

// Same check driven from the procedure side. The usual sequence is consent first,
// visits later, so a violation normally only becomes visible when a visit date is
// recorded — this is the hook that catches it.
export async function autoCheckConsentOnProcedure(studyId, subjectId, user) {
    const rows = await db.select({ consentDate: informedConsents.consentDate })
        .from(informedConsents)
        .where(and(
            eq(informedConsents.studyId, studyId),
            eq(informedConsents.subjectId, subjectId),
            eq(informedConsents.consentType, 'Initial'),
            eq(informedConsents.isWithdrawn, false),
        ));
    if (!rows.length) return null;

    const earliest = rows
        .map(r => String(r.consentDate).slice(0, 10))
        .sort((a, b) => a.localeCompare(b))[0];

    return autoCreateLateConsentDeviation(studyId, subjectId, earliest, user);
}
