#!/usr/bin/env bash
# Execute the automated Operational Qualification (OQ-A) and write the raw
# evidence file that the validation package references.
#
#   ./scripts/run-oq.sh
#
# Exit code is non-zero if any test fails, so this can gate a release.
# Regenerates docs/validation/evidence/OQ-A_RUN.md in full — do not hand-edit
# that file; QA signs the generated record, not a transcription of it.

set -uo pipefail
cd "$(dirname "$0")/.."

OUT=docs/validation/evidence/OQ-A_RUN.md
mkdir -p "$(dirname "$OUT")"

if git diff --quiet && git diff --cached --quiet; then
    TREE="clean"
else
    TREE="MODIFIED — not a frozen release; this run is developmental evidence only"
fi

{
    echo "# OQ-A Automated Test Execution — Raw Evidence"
    echo
    echo "Machine-generated by \`scripts/run-oq.sh\`. Do not edit by hand."
    echo
    echo '```'
    echo "Executed at : $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    echo "Commit      : $(git rev-parse HEAD)"
    echo "Branch      : $(git rev-parse --abbrev-ref HEAD)"
    echo "Tag         : $(git describe --tags --exact-match 2>/dev/null || echo '(none — untagged)')"
    echo "Tree state  : $TREE"
    echo "Node        : $(node -v)"
    echo "npm         : $(npm -v)"
    echo "Platform    : $(uname -s -r -m)"
    echo '```'
    echo
    echo "## Per-script results"
    echo
    echo "| OQ script | Test file | Tests | Pass | Fail | Result |"
    echo "|-----------|-----------|-------|------|------|--------|"
} > "$OUT"

# OQ script id per test file — mirrors the table in ../IQ_OQ_PQ.md
declare -A SCRIPT_ID=(
    [entryrules.test.js]="OQ-A2"   [queryrules.test.js]="OQ-A3"
    [aerules.test.js]="OQ-A4"      [randomrules.test.js]="OQ-A5"
    [dblockrules.test.js]="OQ-A6"  [odm.test.js]="OQ-A7"
    [csvexport.test.js]="OQ-A8"    [audit.test.js]="OQ-A9"
    [rbac-matrix.test.js]="OQ-A10" [rbac-middleware.test.js]="OQ-A10"
    [sitescope.test.js]="OQ-A11"   [tenantscope.test.js]="OQ-A11"
    [consentrules.test.js]="OQ-A12" [iecriteria.test.js]="OQ-A13"
    [visitschedule.test.js]="OQ-A14" [import.test.js]="OQ-A15"
    [license.test.js]="OQ-A16"     [billing.test.js]="OQ-A16"
    [dberrors.test.js]="OQ-A17" [validate.test.js]="OQ-A18"
    [formschema.test.js]="OQ-A19" [isodate.test.js]="OQ-A20"
)

TOTAL=0; TOTAL_PASS=0; TOTAL_FAIL=0; OVERALL=0

for f in tests/*.test.js; do
    base=$(basename "$f")
    raw=$(node --test "$f" 2>&1)
    t=$(printf '%s\n' "$raw" | awk '/^# tests /{print $3; exit}')
    p=$(printf '%s\n' "$raw" | awk '/^# pass /{print $3; exit}')
    fl=$(printf '%s\n' "$raw" | awk '/^# fail /{print $3; exit}')
    t=${t:-0}; p=${p:-0}; fl=${fl:-0}
    if [ "$fl" -eq 0 ] && [ "$t" -gt 0 ]; then res="PASS"; else res="**FAIL**"; OVERALL=1; fi
    printf '| %s | `%s` | %s | %s | %s | %s |\n' \
        "${SCRIPT_ID[$base]:-OQ-A?}" "$base" "$t" "$p" "$fl" "$res" >> "$OUT"
    TOTAL=$((TOTAL+t)); TOTAL_PASS=$((TOTAL_PASS+p)); TOTAL_FAIL=$((TOTAL_FAIL+fl))
done

{
    printf '| **TOTAL** | | **%s** | **%s** | **%s** | ' "$TOTAL" "$TOTAL_PASS" "$TOTAL_FAIL"
    if [ "$OVERALL" -eq 0 ]; then echo "**PASS** |"; else echo "**FAIL** |"; fi
    echo
    echo "## Verdict"
    echo
    if [ "$OVERALL" -eq 0 ]; then
        echo "OQ-A **PASSED** — $TOTAL_PASS of $TOTAL automated checks passed, 0 failed."
    else
        echo "OQ-A **FAILED** — $TOTAL_FAIL of $TOTAL automated checks failed. Raise a deviation."
    fi
    echo
    echo "> This record covers the automated portion of the OQ only. Scripts"
    echo "> OQ-B through OQ-H and the IQ/PQ protocols require a deployed"
    echo "> instance, a database, and named human testers — they are not"
    echo "> executed by this script and remain outstanding."
} >> "$OUT"

echo "Wrote $OUT"
exit $OVERALL
