import { Router } from 'express';
import { eq, and } from 'drizzle-orm';
import { db } from '../db/connection.js';
import { visits, subjects, protocolDeviations } from '../db/schemas/schema.js';
import { requireRole } from '../middleware/rbac.js';
import { writeAudit } from '../lib/audit.js';

const router = Router({ mergeParams: true });

function calcStudyDay(enrollmentDate, actualDate) {
    if (!enrollmentDate || !actualDate) return null;
    const d1 = new Date(enrollmentDate); d1.setHours(0, 0, 0, 0);
    const d2 = new Date(actualDate);     d2.setHours(0, 0, 0, 0);
    return Math.round((d2 - d1) / 86400000) + 1;
}

function calcWindowCompliance(plannedDate, actualDate, windowDays) {
    if (!plannedDate || !actualDate) return null;
    const p = new Date(plannedDate); p.setHours(0, 0, 0, 0);
    const a = new Date(actualDate);  a.setHours(0, 0, 0, 0);
    const diff = Math.round((a - p) / 86400000);
    const win  = windowDays ?? 0;
    if (diff === 0)            return 'On Schedule';
    if (Math.abs(diff) <= win) return diff < 0 ? `Early (${Math.abs(diff)}d)` : `Late (+${diff}d)`;
    if (diff < 0)              return `Early (${Math.abs(diff)}d) — Out of Window`;
    return `Late (+${diff}d) — Out of Window`;
}

// Auto-create a protocol deviation for out-of-window visits (ICH GCP E6(R3) §4.5.3).
// Idempotent: skips if an auto-generated deviation already exists for this visit.
async function autoCreateWindowDeviation(studyId, subjectId, visitId, visitName, actualDate, compliance, user) {
    if (!compliance?.includes('Out of Window')) return null;

    const existing = await db.select({ id: protocolDeviations.id })
        .from(protocolDeviations)
        .where(and(
            eq(protocolDeviations.visitId, visitId),
            eq(protocolDeviations.autoGenerated, true),
        ))
        .limit(1);
    if (existing.length > 0) return null; // already filed

    const today = new Date().toISOString().split('T')[0];
    const [dev] = await db.insert(protocolDeviations).values({
        studyId,
        subjectId,
        visitId,
        autoGenerated:   true,
        deviationType:   'Schedule Deviation',
        category:        'Visit Timing',
        description:     `Visit "${visitName}" was ${compliance}. Auto-detected by system per ICH GCP E6(R3) §4.5.3.`,
        deviationDate:   actualDate ?? today,
        discoveryDate:   today,
        rootCause:       'Visit conducted outside the protocol-defined window.',
        impactOnSubject: 'Under review — to be assessed by investigator.',
        status:          'Open',
        createdBy:       user?.id    ?? null,
        createdByName:   user?.name  ?? 'System',
    }).returning();

    await writeAudit(db, {
        tableName: 'protocol_deviations', recordId: dev.id, action: 'INSERT',
        newValue: dev.description.substring(0, 100),
        reason: 'Auto-generated: visit window deviation detected',
        user, ipAddress: null,
    });
    return dev;
}

// Resolve the :subjectId URL segment and verify it belongs to the active
// study — visits have no study_id of their own, so every handler must anchor
// through the subject (cross-study read/write was possible otherwise).
async function resolveSubject(req) {
    const subjectId = parseInt(req.params.subjectId);
    if (isNaN(subjectId)) return null;
    const [subject] = await db.select().from(subjects)
        .where(and(eq(subjects.id, subjectId), eq(subjects.studyId, req.studyId)));
    if (!subject) return null;
    // Site isolation: PI/investigator/CRC only reach their sites' subjects
    if (Array.isArray(req.siteScope) && !req.siteScope.includes(subject.siteId)) return null;
    return subject;
}

// GET /api/subjects/:subjectId/visits
router.get('/', async (req, res) => {
    try {
        const subject = await resolveSubject(req);
        if (!subject) return res.status(404).json({ error: 'Subject not found in the active study' });
        const rows = await db.select().from(visits)
            .where(eq(visits.subjectId, subject.id))
            .orderBy(visits.visitOrder, visits.createdAt);
        res.json(rows);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// POST /api/subjects/:subjectId/visits
router.post('/', requireRole('investigator', 'pi', 'admin', 'crc'), async (req, res) => {
    try {
        const subjectId = parseInt(req.params.subjectId);
        const {
            visitName, visitOrder, visitType, plannedDate, actualDate,
            windowDays, status, missedReason, formIds,
        } = req.body;
        if (!visitName) return res.status(400).json({ error: 'visitName is required' });

        const subject = await resolveSubject(req);
        if (!subject) return res.status(404).json({ error: 'Subject not found in the active study' });

        const enrollmentDate = subject.enrolledAt ? subject.enrolledAt.toISOString().split('T')[0] : null;
        const studyDay        = calcStudyDay(enrollmentDate, actualDate);
        const windowCompliance = calcWindowCompliance(plannedDate, actualDate, windowDays);

        const [created] = await db.insert(visits).values({
            subjectId,
            visitName,
            visitOrder:      visitOrder ?? null,
            visitType:       visitType  ?? 'Scheduled',
            plannedDate:     plannedDate ?? null,
            actualDate:      actualDate  ?? null,
            windowDays:      windowDays  ?? null,
            studyDay,
            windowCompliance,
            missedReason:    missedReason ?? null,
            createdByName:   req.user.name,
            formIds:         Array.isArray(formIds) ? formIds.map(Number) : [],
            status:          status ?? 'Scheduled',
        }).returning();

        await writeAudit(db, {
            tableName: 'visits', recordId: created.id, action: 'INSERT',
            newValue: visitName, reason: 'Visit created',
            user: req.user, ipAddress: req.ip,
        });

        const autoDeviation = await autoCreateWindowDeviation(
            req.studyId, subjectId, created.id, visitName, actualDate, windowCompliance, req.user,
        ).catch(() => null);

        res.status(201).json({ ...created, autoDeviationFiled: !!autoDeviation });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// PATCH /api/subjects/:subjectId/visits/:id — full update
// (CRA is read-only on clinical data per ROLE_MATRIX — not in this guard.)
router.patch('/:id', requireRole('investigator', 'pi', 'admin', 'crc'), async (req, res) => {
    try {
        const {
            visitName, visitOrder, visitType, plannedDate, actualDate,
            windowDays, status, missedReason, reason, formIds,
        } = req.body;

        const subject = await resolveSubject(req);
        if (!subject) return res.status(404).json({ error: 'Subject not found in the active study' });

        const [existing] = await db.select().from(visits)
            .where(and(eq(visits.id, parseInt(req.params.id)), eq(visits.subjectId, subject.id)));
        if (!existing) return res.status(404).json({ error: 'Visit not found' });
        if (existing.investigatorSigned) {
            return res.status(409).json({ error: 'Visit is signed and cannot be modified. An admin must unsign it first.' });
        }

        const enrollmentDate = subject?.enrolledAt ? subject.enrolledAt.toISOString().split('T')[0] : null;

        const newActualDate  = actualDate  !== undefined ? actualDate  : existing.actualDate;
        const newPlannedDate = plannedDate !== undefined ? plannedDate : existing.plannedDate;
        const newWindowDays  = windowDays  !== undefined ? windowDays  : existing.windowDays;

        const studyDay        = calcStudyDay(enrollmentDate, newActualDate);
        const windowCompliance = calcWindowCompliance(newPlannedDate, newActualDate, newWindowDays);

        const [updated] = await db.update(visits)
            .set({
                visitName:       visitName       ?? existing.visitName,
                visitOrder:      visitOrder      ?? existing.visitOrder,
                visitType:       visitType       ?? existing.visitType,
                plannedDate:     newPlannedDate,
                actualDate:      newActualDate,
                windowDays:      newWindowDays,
                studyDay,
                windowCompliance,
                missedReason:    missedReason    ?? existing.missedReason,
                formIds:         Array.isArray(formIds) ? formIds.map(Number) : existing.formIds,
                status:          status          ?? existing.status,
                updatedAt:       new Date(),
            })
            .where(eq(visits.id, parseInt(req.params.id)))
            .returning();

        await writeAudit(db, {
            tableName: 'visits', recordId: updated.id, action: 'UPDATE',
            fieldName: 'status', oldValue: existing.status, newValue: updated.status,
            reason: reason ?? 'Visit updated',
            user: req.user, ipAddress: req.ip,
        });

        const autoDeviation = await autoCreateWindowDeviation(
            req.studyId, existing.subjectId, updated.id, updated.visitName,
            newActualDate, windowCompliance, req.user,
        ).catch(() => null);

        res.json({ ...updated, autoDeviationFiled: !!autoDeviation });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// PATCH /api/subjects/:subjectId/visits/:id/status
// (CRA is read-only on clinical data per ROLE_MATRIX — not in this guard.)
router.patch('/:id/status', requireRole('investigator', 'pi', 'admin', 'crc'), async (req, res) => {
    try {
        const { status } = req.body;
        const subject = await resolveSubject(req);
        if (!subject) return res.status(404).json({ error: 'Subject not found in the active study' });

        const [updated] = await db.update(visits)
            .set({ status, updatedAt: new Date() })
            .where(and(eq(visits.id, parseInt(req.params.id)), eq(visits.subjectId, subject.id)))
            .returning();
        if (!updated) return res.status(404).json({ error: 'Visit not found' });

        await writeAudit(db, {
            tableName: 'visits', recordId: updated.id, action: 'UPDATE',
            fieldName: 'status', newValue: status,
            user: req.user, ipAddress: req.ip,
        });

        res.json(updated);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// PATCH /api/subjects/:subjectId/visits/:id/sign — Investigator confirms this
// visit's data is final; locks the visit from further edits until unsigned.
router.patch('/:id/sign', requireRole('investigator', 'pi', 'admin'), async (req, res) => {
    try {
        const subject = await resolveSubject(req);
        if (!subject) return res.status(404).json({ error: 'Subject not found in the active study' });

        const [existing] = await db.select().from(visits)
            .where(and(eq(visits.id, parseInt(req.params.id)), eq(visits.subjectId, subject.id)));
        if (!existing) return res.status(404).json({ error: 'Visit not found' });
        if (existing.investigatorSigned) return res.status(409).json({ error: 'Visit is already signed' });

        const [signed] = await db.update(visits)
            .set({
                investigatorSigned:       true,
                investigatorSignedAt:     new Date(),
                investigatorSignedBy:     req.user.id,
                investigatorSignedByName: req.user.name,
                updatedAt:                new Date(),
            })
            .where(eq(visits.id, existing.id))
            .returning();

        await writeAudit(db, {
            tableName: 'visits', recordId: existing.id, action: 'SIGN',
            reason: 'Investigator signed off — visit data confirmed final',
            user: req.user, ipAddress: req.ip,
        });

        res.json(signed);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// PATCH /api/subjects/:subjectId/visits/:id/unsign — admin only
router.patch('/:id/unsign', requireRole('admin'), async (req, res) => {
    try {
        const { reason } = req.body;
        if (!reason?.trim()) return res.status(400).json({ error: 'Unsign reason is required' });

        const subject = await resolveSubject(req);
        if (!subject) return res.status(404).json({ error: 'Subject not found in the active study' });

        const [existing] = await db.select().from(visits)
            .where(and(eq(visits.id, parseInt(req.params.id)), eq(visits.subjectId, subject.id)));
        if (!existing) return res.status(404).json({ error: 'Visit not found' });
        if (!existing.investigatorSigned) return res.status(409).json({ error: 'Visit is not signed' });

        const [unsigned] = await db.update(visits)
            .set({
                investigatorSigned:         false,
                investigatorUnsignedAt:     new Date(),
                investigatorUnsignedBy:     req.user.id,
                investigatorUnsignedByName: req.user.name,
                investigatorUnsignReason:   reason,
                updatedAt:                  new Date(),
            })
            .where(eq(visits.id, existing.id))
            .returning();

        await writeAudit(db, {
            tableName: 'visits', recordId: existing.id, action: 'UNLOCK',
            reason, user: req.user, ipAddress: req.ip,
        });

        res.json(unsigned);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// DELETE /api/subjects/:subjectId/visits/:id
router.delete('/:id', requireRole('investigator', 'pi', 'admin'), async (req, res) => {
    try {
        const visitId = parseInt(req.params.id);
        const { reason } = req.body;
        if (!reason?.trim()) return res.status(400).json({ error: 'reason is required' });

        const subject = await resolveSubject(req);
        if (!subject) return res.status(404).json({ error: 'Subject not found in the active study' });

        const [existing] = await db.select().from(visits)
            .where(and(eq(visits.id, visitId), eq(visits.subjectId, subject.id)));
        if (!existing) return res.status(404).json({ error: 'Visit not found' });
        if (existing.investigatorSigned) {
            return res.status(409).json({ error: 'Visit is signed and cannot be deleted. An admin must unsign it first.' });
        }

        await db.delete(visits).where(eq(visits.id, visitId));

        await writeAudit(db, {
            tableName: 'visits', recordId: visitId, action: 'DELETE',
            oldValue: existing.visitName, reason,
            user: req.user, ipAddress: req.ip,
        });

        res.json({ message: 'Visit deleted' });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

export default router;
